### ISSUE TITLE
Tidy up readme.md

### ISSUE THREAD

**Issue by alexmackey** [telstrapurple/DevEvents#74]
There is rather a lot of content in readme.md. 

Suggest moving out the following to other pages:

- [x] Honorable mentions (now closed as well)
- [x] 2019 events
- [ ] CFP
- [x] To be confirmed

Not sure about completed events that can probably stay

**Comment by luizbon** [comment]
It seems that the readme.md got an organic organisation with previous years moving to a separate file and the current year on the main file.
By the end of each year, people start to add the next events and it organically self-organise.

I understand the idea of keeping the main readme clean, but at the same time I think is good to have access to all events from the main page.

Maybe we can start to send the past events directly to a separate page?

**Comment by yashints** [comment]
I would say the current year's events in the main page and links to previous year's at the top like a table of content. Thoughts?

**Comment by alexmackey** [comment]
I'm going to have a play with this today. I think this years events should be easily accessible but its also nice to have quick access to the previous years events on the same page as you can see what might be coming up this year.

**Comment by alexmackey** [comment]
Do you think we should just have 2019 events and remove the completed section? Just would save some updates and make it look current. There are not so many events that its hard to scroll through?

**Comment by luizbon** [comment]
I think is fair enough.
When close to 2020 we can start a new table on the main file and as soon as the year change, move the old year to a new file keeping the rest.

**Comment by yashints** [comment]
Should we close this @alexmackey?

**Comment by glav** [comment]
Most of this is done and this issue is super old, so closing. Can open new issues for specific fixes.
